name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'x3gallery/**'
      - '.github/workflows/publish-helm.yaml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package chart
        run: |
          mkdir -p charts
          helm package x3gallery -d charts

      - name: Create or update index.yaml
        run: |
          if [ -f charts/index.yaml ]; then
            helm repo index charts --url https://ramuskay.github.io/hc-x3gallery/ --merge charts/index.yaml
          else
            helm repo index charts --url https://ramuskay.github.io/hc-x3gallery/
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./charts
          publish_branch: gh-pages
          keep_files: true
          force_orphan: false
          commit_message: "Publish Helm chart"
